### ISSUE TITLE
Deposit doesn't use configured currency

### ISSUE THREAD

**Issue by cribbstechnologies** [alfonsogoberjr/gdax-lambda-buyer#4]
USD is hardcoded in the deposit method

https://github.com/alfonsogoberjr/gdax-lambda-buyer/blob/master/handler.js#L41

Should be `process.env.FIAT_TYPE` instead

Addressed in PR 5
https://github.com/alfonsogoberjr/gdax-lambda-buyer/pull/5

**Comment by alfonsogober** [comment]
Just merged. Closing
